services:


  minio:
    image: "quay.io/minio/minio:RELEASE.2025-03-12T18-04-18Z"
    env_file:
      - .env 
    hostname: "${MINIO_HOSTNAME}"
    container_name: "minio"
    ports:
      - "127.0.0.1:9900:9000"
      - "127.0.0.1:9901:9001"
    volumes:
      - ./minio/data:/export 
      - ./minio/config:/root/.minio
    networks:
      - csura 
    command: ["server", "--console-address", ":9001", "/data"]
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

  createbuckets:
    image: quay.io/minio/mc:RELEASE.2025-03-12T17-29-24Z
    container_name: "minio-client"
    depends_on:
      - minio 
    env_file:
      - .env 
    volumes:
      - ./bootstrap.sh:/bootstrap.sh 
      - ./policies:/policies
    networks:
      - csura 
    restart: on-failure 
    entrypoint: /bin/bash /bootstrap.sh
  
networks:
  csura: 
    name: csura 
    driver: bridge 